#!/bin/bash -e 

TAG=$1

if [ -z ${TAG} ]
then
  echo "docker tag as the first argument pretty please"
  exit 1
fi


BASE_IMAGE=ubuntu:17.04

set -x

SHA1=$(git rev-parse --short=12 HEAD)

SAWTOOTH_DIR=$(cd $(dirname $(dirname $0)) && pwd)

rm -rf ${SAWTOOTH_DIR}/wheels

##
## build the wheels for sawtooth_signing
##

docker run --rm -it             \
   -v ${SAWTOOTH_DIR}:/sawtooth \
   ${BASE_IMAGE}                \
   /sawtooth/bin/build_wheels

##
## build the python sdk
##

IMAGE=docker-internal.pokitdok.com/sawtooth-base:${TAG}

docker build                                              \
  --tag ${IMAGE}                                          \
  --label intel.sawtooth-core.sha1=${SHA1}                \
  -f Dockerfile.sdk                                       \
  .


function build_image () {
   SAWTOOTH_IMAGE_NAME=docker-internal.pokitdok.com/$1
   PYDIR=$2

docker build \
  --tag ${SAWTOOTH_IMAGE_NAME} \
  - <<EOF

FROM ${IMAGE}
RUN cd ${PYDIR} && python3 setup.py install
EOF

}

build_image sawtooth-validator /sawtooth/validator
build_image sawtooth-rest-api /sawtooth/rest_api
build_image sawtooth-settings /sawtooth/families/settings

