FROM ubuntu:17.04

RUN apt-get update \
    && apt-get install -y \
        python3           \
        python3-pip       \
        pkg-config        \
        libffi-dev        \
        libsecp256k1-0    \
        libsecp256k1-dev  \
        libzmq3-dev       \
    && rm -rf /var/lib/apt/lists/*

ADD . /sawtooth
RUN pip3 install /sawtooth/wheels/*.whl

RUN pip3 install grpcio-tools   \
    && /sawtooth/bin/protogen   \
    && cd /sawtooth/sdk/python  \
    && python3 setup.py install

